### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by dajoho** [catalinionita/Ecryptfs-Tools-for-Android#31]
I am trying to build this outside of the AOSP tree. Is this possible? Is the project dead? I wrote you an email but got no response..

**Comment by catalinionita** [comment]
Hi! I stopped working on the project some time ago. If you want to build outside of AOSP you can try the Linux version of the package: https://www.archlinux.org/packages/?name=ecryptfs-utils.

--Catalin

**Comment by dajoho** [comment]
Thanks! I'm unfortunately looking for your specific version, as it was used in a chinese gaming console firmware that I'm debugging. Looks like I am going to have to compile android 4!

Thank you for the reply!
